### ISSUE TITLE
Training and Evaluation 

### ISSUE THREAD

**Issue by abdullahfathi** [dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings#1]
Could you provide a script for training and evaluation, I am not able to find it in your code. Thanks

**Comment by Demirrr** [comment]
Dear @abdullahfathi,

thank you for your interest. Executing [search.py ](https://github.com/dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings/blob/main/search.py) results in training and evaluating models while applying the grid-search over the defined parameter ranges. More specifically, the [Experiment class](https://github.com/dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings/blob/main/util/experiment.py) implements a method that combines [KvsAll training](https://github.com/dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings/blob/bfe4b1126774e8d621d15d38feabc4049377764f/util/experiment.py#L252) and [Link prediction evaluation](https://github.com/dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings/blob/bfe4b1126774e8d621d15d38feabc4049377764f/util/experiment.py#L79) phases.
