### ISSUE TITLE
I cant find this model, Where can I find it?

### ISSUE THREAD

**Issue by abdullahfathi** [dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings#3]
https://github.com/dice-group/Convolutional-Complex-Knowledge-Graph-Embeddings/blob/6212a48188d4311d3b382f83c4682829a1060641/util/experiment.py#L4

**Comment by Demirrr** [comment]
Dear @abdullahfathi,

I added extra comments in the code for the sake of the readability and modify the package imports. I kindly ask you to update your local repository. By executing the following three lines, one should be able to run ConEx without an issue.

1. `conda env create -f environment.yml`
2. `source activate conex`
3. `python search.py`

I will close this issue. Please reopen it if necessary.
